application:
  issue:
    max-allowed-books: 2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryDB?createDatabaseIfNotExist=TRUE
    username: root
    password: lokation
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-message: always
