application:
  issue:
    maxAllowedBooks: 2
#    max-allowed-books: 2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryDB?createDatabaseIfNotExist=TRUE
    username: root
    password: lokation
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: security_oauth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master #по этому адресу работает котейнер oauth 2.0 (JSON)
server:
  error:
    include-message: always
  port: 8081
